language: node_js
node_js:
node_js:
  - 'stable'
  - 'lts/*'
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
script: "npm run test"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: npm
  email: "eiurur789@gmail.com"
  api_key: $NPM_API_KEY
  skip_cleanup: true # `run-script build`で生成したES5のコードを消さないようにする
  on:
    tags: true