language: node_js
node_js:
node_js:
  - 'stable'
  - 'lts/*'
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
script: "npm run test"
env:
  - CXX=g++-4.8
addons:
  apt:
    packages:
      - g++-4.8
